name: Tech debt
description: Cleanup, refactor, or infrastructure improvements
title: "[Tech Debt] "
labels: ["type:tech-debt"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Why this improvement is needed
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: In/out of scope
    validations:
      required: true
  - type: textarea
    id: plan
    attributes:
      label: Plan
      description: Steps to execute, risks
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Clear, testable outcomes
    validations:
      required: true
  - type: input
    id: estimate
    attributes:
      label: Estimate (hours)
