import { Card, CardContent } from '@/components/ui/card'
import { ScrollArea } from '@/components/ui/scroll-area'
import type { BarcodeItem } from '@/api/services/barcodes.service'

interface BarcodePreviewProps {
  barcodes: BarcodeItem[]
  paperSetting: string
}

const paperDimensions: Record<string, { width: string; height: string; cols: number }> = {
  '1': { width: '38mm', height: '25mm', cols: 4 }, // Roll 38mm x 25mm
  '2': { width: '50mm', height: '25mm', cols: 3 }, // Roll 50mm x 25mm
  '3': { width: '29.7mm', height: '33.9mm', cols: 7 }, // A4 sheet (28 labels)
}

export function BarcodePreview({ barcodes, paperSetting }: BarcodePreviewProps) {
  const dims = paperDimensions[paperSetting] || paperDimensions['1']

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          Total: <span className="font-semibold">{barcodes.length}</span> barcodes to print
        </p>
      </div>

      <ScrollArea className="h-96 border rounded-lg p-4 bg-muted/50">
        <div className={`grid gap-2 grid-cols-${dims.cols}`} style={{ gridTemplateColumns: `repeat(${dims.cols}, 1fr)` }}>
          {barcodes.map((barcode) => (
            <Card
              key={barcode.id}
              className="overflow-hidden"
              style={{
                width: dims.width,
                height: dims.height,
              }}
            >
              <CardContent className="p-2 h-full flex flex-col justify-center items-center text-center text-xs">
                {barcode.business_name && (
                  <div className="text-[8px] font-semibold truncate w-full">{barcode.business_name}</div>
                )}

                {barcode.barcode_svg && (
                  <div
                    className="my-1"
                    // SVG generated by backend barcode service - safe HTML
                    dangerouslySetInnerHTML={{ __html: barcode.barcode_svg }}
                    style={{ maxHeight: '60%', maxWidth: '100%' }}
                  />
                )}

                {barcode.product_code && (
                  <div className="text-[8px] truncate w-full">{barcode.product_code}</div>
                )}

                {barcode.product_price && (
                  <div className="text-[8px] font-semibold">${barcode.product_price.toFixed(2)}</div>
                )}

                {barcode.packing_date && (
                  <div className="text-[8px] text-muted-foreground">{barcode.packing_date}</div>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      </ScrollArea>

      <p className="text-xs text-muted-foreground">
        Preview shows {dims.cols} columns layout. Actual print output will format accordingly.
      </p>
    </div>
  )
}
